# Generated by Django 3.1 on 2020-08-12 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=200)),
                ('initdate', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(max_length=200)),
            ],
        ),
    ]
