# Generated by Django 3.1 on 2020-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200812_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='identification',
            field=models.TextField(max_length=200),
        ),
    ]
